// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://cczhdrwgsirbiqqqffzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjemhkcndnc2lyYmlxcXFmZnp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExNzY0NjMsImV4cCI6MjA3Njc1MjQ2M30.XDZtvxMnHoQ_nVnD0NQyTa4C6r7dHGK08-hvuqC3yHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);